### ISSUE TITLE
PDF API Buildout

### ISSUE THREAD

**Issue by OGHP** [diego-ramos130/pptt#20]

**Comment by canned-ice** [comment]
Added function makePDF() to server.js, still needs to be called at some point, but works!

**Comment by canned-ice** [comment]
**User Story:**
As a _user_, I want to be able to download my project's dashboard as a pdf to share.
As a _developer_, I want to be able to utilize a Node.js module to create a pdf from our dynamic website, including design elements from our css files and data from our database.
